'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase'

type Row={id:string;slug:string;title:string;category:string;excerpt:string;body:string;author:string;published:boolean}
export default function ArticleManager(){const [rows,setRows]=useState<Row[]>([]);const [row,setRow]=useState<Row|null>(null);const [setup,setSetup]=useState('');const [msg,setMsg]=useState('');const [ready,setReady]=useState(false);const db=createClient()
 async function load(){const {data,error}=await db.from('articles').select('*').order('created_at',{ascending:false});if(error){setMsg('اتصال به پایگاه داده برقرار نشد.')}else setRows((data||[]) as Row[])}
 useEffect(()=>{db.auth.getUser().then(({data})=>{if(data.user){setReady(true);load()}else location.href='/signin'})},[])
 async function claim(){const {data,error}=await db.rpc('claim_admin',{setup_token:setup});if(error||!data){setMsg('کد راه‌اندازی نامعتبر است.')}else{setMsg('دسترسی مدیر فعال شد.');load()}}
 async function save(e:any){e.preventDefault();if(!row)return;const payload={slug:row.slug,title:row.title,category:row.category,excerpt:row.excerpt,body:row.body,author:row.author,published:row.published,published_at:row.published?new Date().toISOString():null,updated_at:new Date().toISOString()};const q=row.id?db.from('articles').update(payload).eq('id',row.id):db.from('articles').insert(payload);const {error}=await q;if(error)setMsg('ذخیره انجام نشد؛ ابتدا دسترسی مدیر را فعال کنید.');else{setMsg('مقاله ذخیره شد.');setRow(null);load()}}
 async function remove(id:string){if(!confirm('این مقاله حذف شود؟'))return;const {error}=await db.from('articles').delete().eq('id',id);setMsg(error?'حذف انجام نشد.':'مقاله حذف شد.');load()}
 if(!ready)return <main className="authPage"><div className="authCard">در حال بررسی ورود…</div></main>
 return <main className="adminPage"><div className="container"><div className="adminTop"><div><a href="/" className="logo">Rahayi<span>رهایی</span></a><h1>مدیریت مطالب</h1></div><button onClick={async()=>{await db.auth.signOut();location.href='/'}}>خروج</button></div>{msg&&<p className="notice">{msg}</p>}<section className="setup"><strong>راه‌اندازی مدیر اول</strong><p>کد یک‌بارمصرف راه‌اندازی را وارد کنید.</p><input value={setup} onChange={e=>setSetup(e.target.value)} placeholder="کد راه‌اندازی"/><button onClick={claim}>فعال‌سازی</button></section><div className="adminActions"><button className="cta" onClick={()=>setRow({id:'',slug:'',title:'',category:'تحلیل',excerpt:'',body:'',author:'تحریریه رهایی',published:false})}>+ مقاله جدید</button></div><div className="adminList">{rows.map(r=><div className="adminRow" key={r.id}><div><b>{r.title}</b><span>{r.category} · {r.published?'منتشر شده':'پیش‌نویس'}</span></div><div><button onClick={()=>setRow(r)}>ویرایش</button><button onClick={()=>remove(r.id)}>حذف</button></div></div>)}</div>{row&&<form className="editor" onSubmit={save}><h2>{row.id?'ویرایش مقاله':'مقاله جدید'}</h2><input value={row.title} onChange={e=>setRow({...row,title:e.target.value})} placeholder="عنوان" required/><input value={row.slug} onChange={e=>setRow({...row,slug:e.target.value})} placeholder="slug انگلیسی" required/><input value={row.category} onChange={e=>setRow({...row,category:e.target.value})} placeholder="دسته‌بندی"/><input value={row.author} onChange={e=>setRow({...row,author:e.target.value})} placeholder="نویسنده"/><textarea value={row.excerpt} onChange={e=>setRow({...row,excerpt:e.target.value})} placeholder="خلاصه"/><textarea className="bodyInput" value={row.body} onChange={e=>setRow({...row,body:e.target.value})} placeholder="متن مقاله" required/><label className="check"><input type="checkbox" checked={row.published} onChange={e=>setRow({...row,published:e.target.checked})}/> انتشار مقاله</label><button className="cta" type="submit">ذخیره</button><button type="button" onClick={()=>setRow(null)}>انصراف</button></form>}</div></main>}